### ISSUE TITLE
Hanged Sublime

### ISSUE THREAD

**Issue by moltar** [icylace/CursorRuler#6]
The idea is good. However, in SL2 it is very slow and when I tried to open command panel to remove this plugin, SL hanged completely. Two times in a row.

**Comment by icylace** [comment]
I'll check this out when I can.  Thanks!

**Comment by askeeve** [comment]
I would just like to second that I was having this issue today as well.  Package Control finally updated and with CursorRuler installed ST2's process would eat up all the available memory on my system and hang.  I was able to uninstall and resolve by deleting CursorRuler from the packages directory and then Removing it with Package Control as quickly as I could when I started Sublime.  

Looks like some kind of memory leak in any case.

**Comment by psalaets** [comment]
I had the same issue in ST2 on OS X. I was able to remove the package manually:

1. Close Sublime 
2. `rm -rf ~/Library/Application Support/Sublime Text 2/Packages/CursorRuler`
3. Remove "CursorRuler" from the `installed_packages` array in `~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/Package\ Control.sublime-settings`

**Comment by icylace** [comment]
I released an update which should take care of the ST2 crashing bug described here.

Note that the other ST2 crashing bug described at https://github.com/icylace/CursorRuler#known-major-bug-for-sublime-text-2-only unfortunately still exists.
