### ISSUE TITLE
I can't remove this plugin

### ISSUE THREAD

**Issue by serkanyersen** [icylace/CursorRuler#7]
I tried disabling, toggling, completely removing it. vertical ruler just won't go away? what to do?

**Comment by serkanyersen** [comment]
ok, not just ingored_packages but if you also toggle to disable first and remove the package, it becomes permanent. I think you should point this out in the messages.txt

**Comment by icylace** [comment]
I do talk about this in the readme [here](https://github.com/icylace/CursorRuler#known-minor-bugs) but pointing it out in messages.txt is a good idea.  I'll also check out the disabling scenario you brought up.  I'll do that when I can.  Thanks!

**Comment by icylace** [comment]
In the newest version I was finally able to have the dynamic cursor rulers cleared properly when CursorRuler is disabled or toggled off.
